### ISSUE TITLE
Life example tries to open html file in wrong path

### ISSUE THREAD

**Issue by misterspeedy** [ChrisNikkel/SharpVG#39]
When running the Life example:

    PS C:\code\SharpVG> dotnet run -p Examples/Life/Life.fsproj

I get:

```
Unhandled exception. System.ComponentModel.Win32Exception (2): The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Helpers.File.openFile(String name) in C:\code\SharpVG\Helpers\File.fs:line 25
   at LifeExample.main(String[] argv) in C:\code\SharpVG\Examples\Life\Life.fs:line 128
```

This seems to be because the `Life.html` file is created in the `SharpVG` directory, but the call to `Helpers.File.openFile` ends up looking somewhere else.

**Comment by ChrisNikkel** [comment]
Fixed.  Thanks for pointing these issues out to me.
